services:
  web:
    # Use the image built from the base config
    image: fastapi-postgres-app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/code # Bind mount for live code changes
    environment: .env.dev
    depends_on:
      - db # Ensure DB starts first
  db:
    ports:
      - "5432:5432" # Expose port for local development
