[project]
name = "fastapi-template"
dynamic = ["version"]
dependencies = [
    "alembic>=1.18.1",
    "asyncpg>=0.31.0",
    "fastapi-users[sqlalchemy]>=15.0.3",
    "fastapi[standard]>=0.128.0",
    "pydantic-settings>=2.12.0",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.40.0",
]
